__all__ = [
    "DEFAULT_JAVA_PORT",
    "DEFAULT_PYTHON_PORT",
    "DEFAULT_GENIUS_NEGOTIATOR_TIMEOUT",
]
DEFAULT_JAVA_PORT = 25337
DEFAULT_PYTHON_PORT = 25338
DEFAULT_GENIUS_NEGOTIATOR_TIMEOUT = 180
