# negmas documentation build configuration file
# Originally created by sphinx-quickstart on Fri Jun  9 13:47:02 2017.
# Modernized configuration for Furo theme - optimized for build speed.

from __future__ import annotations

from importlib.metadata import version as get_version
from pathlib import Path

# -- General configuration ---------------------------------------------

# Extensions - minimal set for speed
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    # "sphinx.ext.viewcode",  # Disabled for speed - adds source code to docs
    "sphinx.ext.linkcode",  # Lightweight alternative - links to GitHub
    "nbsphinx",
    "sphinx_tabs.tabs",
    "sphinx_click",  # Auto-generate docs for Click CLIs
    "sphinxcontrib.typer",  # Auto-generate docs for Typer CLIs
]

# Try to load optional extensions
_has_copybutton = False
try:
    import sphinx_copybutton  # noqa: F401

    extensions.append("sphinx_copybutton")
    _has_copybutton = True
except ImportError:
    pass

# Intersphinx - external documentation links
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The root document.
root_doc = "index"

# General information about the project.
project = "NegMAS"
copyright = "2018-2025, Yasser Mohammad"
author = "Yasser Mohammad"

# Read version from package metadata
try:
    version = get_version("negmas")
except Exception:
    version = "0.13.0"

# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**.ipynb_checkpoints",
    "**/test_*",
    "**/tests/**",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "friendly"
pygments_dark_style = "monokai"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------

# Use Furo theme - a modern, clean theme with dark mode support
html_theme = "furo"

# Theme options for Furo
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#2980B9",
        "color-brand-content": "#2980B9",
    },
    "dark_css_variables": {
        "color-brand-primary": "#56B4E9",
        "color-brand-content": "#56B4E9",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_buttons": ["view", "edit"],
    "source_repository": "https://github.com/yasserfarouk/negmas",
    "source_branch": "master",
    "source_directory": "docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
_docs_dir = Path(__file__).parent
_static_dir = _docs_dir / "_static"
if _static_dir.exists():
    html_static_path = ["_static"]
    # Custom CSS to override theme defaults if needed
    if (_static_dir / "custom.css").exists():
        html_css_files = ["custom.css"]
else:
    html_static_path = []

# Speed optimizations for HTML output
html_domain_indices = False  # Don't generate domain indices
html_copy_source = False  # Don't copy source files
html_show_sourcelink = False  # Don't show source links (using linkcode instead)

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "negmasdoc"

# -- Options for LaTeX output ------------------------------------------

latex_elements = {"papersize": "a4paper", "pointsize": "10pt", "figure_align": "htbp"}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (root_doc, "negmas.tex", "NegMAS Documentation", "Yasser Mohammad", "manual")
]

# -- Options for manual page output ------------------------------------

man_pages = [(root_doc, "negmas", "NegMAS Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------

texinfo_documents = [
    (
        root_doc,
        "negmas",
        "NegMAS Documentation",
        author,
        "NegMAS",
        "NEGotiations Managed by Agent Simulations.",
        "Miscellaneous",
    )
]

# -- Extension configuration -------------------------------------------

default_role = "any"

# Autodoc settings - optimized for speed
autodoc_typehints = "signature"
autodoc_typehints_format = "short"  # Don't include full module paths
autodoc_inherit_docstrings = False  # Don't inherit docstrings (faster)
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "private-members": False,
    "inherited-members": False,
    "show-inheritance": True,
}

# Mock heavy imports that aren't needed for doc generation
autodoc_mock_imports = [
    "py4j",
    "java",
    "torch",
    "tensorflow",
    "sklearn",
    "joblib",
    "dill",
    "cloudpickle",
    "ray",
    "distributed",
]

# Don't set TYPE_CHECKING flag (can cause import issues)
set_type_checking_flag = False

# Autosummary settings
autosummary_generate = False  # Don't auto-generate stub files


# Linkcode extension - link to GitHub instead of embedding source
def linkcode_resolve(domain, info):
    """Generate GitHub links for source code."""
    if domain != "py":
        return None
    if not info["module"]:
        return None

    filename = info["module"].replace(".", "/")
    return f"https://github.com/yasserfarouk/negmas/blob/main/src/{filename}.py"


# Napoleon settings for docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Copy button configuration - don't copy prompts (only if extension is loaded)
if _has_copybutton:
    copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
    copybutton_prompt_is_regexp = True

# nbsphinx configuration
nbsphinx_execute = "never"
nbsphinx_allow_errors = True

# Suppress warnings for cleaner output
suppress_warnings = ["ref.any", "toc.excluded"]

# Nitpicky mode off (faster, fewer checks)
nitpicky = False
