# negmas documentation build configuration file
# Originally created by sphinx-quickstart on Fri Jun  9 13:47:02 2017.
# Modernized configuration for Furo theme.

from __future__ import annotations

from importlib.metadata import version as get_version
from pathlib import Path

# -- General configuration ---------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.coverage",
    "sphinx.ext.napoleon",
    "sphinx.ext.githubpages",
    "sphinx.ext.graphviz",
    "sphinx.ext.autosummary",
    "sphinx_automodapi.automodapi",
    "sphinx.ext.intersphinx",
    "sphinx_automodapi.smart_resolver",
    "sphinx.ext.mathjax",
    "nbsphinx",
    "sphinx_tabs.tabs",
]

# Try to load optional extensions
_has_copybutton = False
try:
    import sphinx_copybutton  # noqa: F401

    extensions.append("sphinx_copybutton")
    _has_copybutton = True
except ImportError:
    pass

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The root document.
root_doc = "index"

# General information about the project.
project = "NegMAS"
copyright = "2018-2025, Yasser Mohammad"
author = "Yasser Mohammad"

# Read version from package metadata
try:
    version = get_version("negmas")
except Exception:
    version = "0.13.0"

# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "friendly"
pygments_dark_style = "monokai"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------

# Use Furo theme - a modern, clean theme with dark mode support
html_theme = "furo"

# Theme options for Furo
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#2980B9",
        "color-brand-content": "#2980B9",
    },
    "dark_css_variables": {
        "color-brand-primary": "#56B4E9",
        "color-brand-content": "#56B4E9",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_buttons": ["view", "edit"],
    "source_repository": "https://github.com/yasserfarouk/negmas",
    "source_branch": "master",
    "source_directory": "docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
_docs_dir = Path(__file__).parent
_static_dir = _docs_dir / "_static"
if _static_dir.exists():
    html_static_path = ["_static"]
    # Custom CSS to override theme defaults if needed
    if (_static_dir / "custom.css").exists():
        html_css_files = ["custom.css"]
else:
    html_static_path = []

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = "_static/logo.png"

# The name of an image file to use as favicon.
# html_favicon = "_static/favicon.ico"

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "negmasdoc"

# -- Options for LaTeX output ------------------------------------------

latex_elements = {"papersize": "a4paper", "pointsize": "10pt", "figure_align": "htbp"}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (root_doc, "negmas.tex", "NegMAS Documentation", "Yasser Mohammad", "manual")
]

# -- Options for graphviz used in inheritance diagrams -----------------

inheritance_graph_attrs = dict(rankdir="TB", fontsize=11, size='""')
inheritance_node_attrs = dict(fontsize=11)

# -- Options for manual page output ------------------------------------

man_pages = [(root_doc, "negmas", "NegMAS Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------

texinfo_documents = [
    (
        root_doc,
        "negmas",
        "NegMAS Documentation",
        author,
        "NegMAS",
        "NEGotiations Managed by Agent Simulations.",
        "Miscellaneous",
    )
]

# -- Extension configuration -------------------------------------------

default_role = "any"

imgmath_image_format = "png"

# If false, no module index is generated.
html_domain_indices = True

automodsumm_inherited_members = True

autodoc_typehints = "signature"
set_type_checking_flag = True

# Napoleon settings for docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Copy button configuration - don't copy prompts (only if extension is loaded)
if _has_copybutton:
    copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
    copybutton_prompt_is_regexp = True

# nbsphinx configuration
nbsphinx_execute = "never"
nbsphinx_allow_errors = True
